import pandas as pd
import joblib
df = pd.read_csv("creditcard.csv")
print("First 5 rows:")
print(df.head())
print("\nDataset Shape:")
print(df.shape)
print("\nColumns:")
print(df.columns)
print("\nClass Distribution:")
print(df["Class"].value_counts())
print("\nMissing Values:")
print(df.isnull().sum())
print("\nDuplicate Rows:")
print(df.duplicated().sum())
df = df.drop_duplicates()
print("\nDataset Shape After Removing Duplicates:")
print(df.shape)
print("\nDuplicate Rows After Cleaning:")
print(df.duplicated().sum())
import matplotlib.pyplot as plt
class_counts = df["Class"].value_counts()
print("\nTransaction Counts:")
print(class_counts)
class_counts.plot(kind="bar")
plt.title("Normal Transactions vs Fraudulent Transactions")
plt.xlabel("Transaction Class")
plt.ylabel("Number of Transactions")
plt.xticks([0, 1], ["Normal (0)", "Fraud (1)"], rotation=0)
plt.show()
X = df.drop("Class", axis=1)
y = df["Class"]
print("\nFeatures (X) shape:")
print(X.shape)
print("\nTarget (y) shape:")
print(y.shape)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)
print("\nTraining data shape:")
print(X_train.shape)
print("\nTesting data shape:")
print(X_test.shape)
print("\nTraining target distribution:")
print(y_train.value_counts())
print("\nTesting target distribution:")
print(y_test.value_counts())
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print("\nScaled training data shape:")
print(X_train_scaled.shape)
print("\nScaled testing data shape:")
print(X_test_scaled.shape)
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
print("\nTraining the model...")
model.fit(X_train_scaled, y_train)
print("Model training completed!")
y_pred = model.predict(X_test_scaled)
print("\nPredictions completed!")
print("\nFirst 20 Predictions:")
print(y_pred[:20])
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
print("\nModel Performance:")
print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
y_pred = model.predict(X_test_scaled)
print("\nModel Evaluation:")
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
import matplotlib.pyplot as plt
import seaborn as sns
cm = confusion_matrix(y_test, y_pred)                                                                                                                                                                                                                                                                                                                                                                                                                                   
print("\nConfusion Matrix:")
print(cm)
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix - Credit Card Fraud Detection")
plt.show()
joblib.dump(model, "fraud_detection_model.pkl")
joblib.dump(scaler, "scaler.pkl")
print("\nModel and scaler saved successfully!")
